import { prisma } from '@/lib/db'
import type { Prisma } from '@prisma/client'
import type {
    ActualizarAutorizacionInput,
    ActualizarContextoFacturacionInput,
    ActualizarLoteFacturacionInput,
    ActualizarPrestacionFacturacionInput,
    BusquedaFacturacionInput,
    BusquedaLotesInput,
    CargarOrdenesFacturacionInput,
    CrearLoteFacturacionInput,
    CrearMedicacionFacturacionInput,
    CrearPracticaFacturacionInput,
} from './schemas'
import type {
    AdmisionFacturacionListItem,
    EstadoLote,
    FacturacionContexto,
    LoteFacturacionDetalle,
    LoteFacturacionItemDetalle,
    LoteFacturacionListItem,
    OrdenAutorizadaLote,
    OrdenFacturacionResultado,
    PrestacionFacturableItem,
} from './types'
import { crearOrdenAmbulatorio, crearOrdenesAmbulatoriasPorPractica } from '@/modules/orden/service'
import type { CrearOrdenInput } from '@/modules/orden/schemas'
import { calcularImporteFacturable, resolverReglaFacturacion } from './cobertura'

const MS_POR_DIA = 24 * 60 * 60 * 1000

function normalizarCodigoPractica(codigoPractica: string): string {
    return codigoPractica.trim().slice(0, 8).toUpperCase()
}

async function obtenerValoresPracticas(codigosPractica: string[]): Promise<Map<string, number>> {
    const codigos = Array.from(
        new Set(codigosPractica.map(normalizarCodigoPractica).filter(Boolean))
    )

    if (codigos.length === 0) return new Map()

    const prestaciones = await prisma.nomencladorPrestacion.findMany({
        where: { codigo: { in: codigos } },
        select: { codigo: true, valor: true },
    })

    const result = new Map(
        prestaciones.map((prestacion) => [normalizarCodigoPractica(prestacion.codigo), Number(prestacion.valor ?? 0)])
    )

    // Fallback: para códigos sin precio en el nomenclador, buscar el último precio
    // unitario conocido en prácticas ya facturadas con el mismo código.
    const sinPrecio = codigos.filter((c) => !result.has(c) || result.get(c) === 0)
    if (sinPrecio.length > 0) {
        const codigosConEspacio = sinPrecio.map((c) => c.padEnd(8, ' '))
        const historicos = await prisma.practica.findMany({
            where: {
                codigoPractica: { in: codigosConEspacio },
                importeTotal: { not: null, gt: 0 },
                cantidad: { gt: 0 },
            },
            orderBy: { id: 'desc' },
            select: { codigoPractica: true, importeTotal: true, cantidad: true },
            take: sinPrecio.length * 10,
        })

        for (const h of historicos) {
            const clave = normalizarCodigoPractica(h.codigoPractica)
            if (!result.has(clave) || result.get(clave) === 0) {
                const precioUnitario = Number(h.importeTotal) / Number(h.cantidad)
                if (precioUnitario > 0) result.set(clave, precioUnitario)
            }
        }
    }

    return result
}

export async function obtenerValorPractica(codigoPractica: string): Promise<number> {
    const valores = await obtenerValoresPracticas([codigoPractica])
    return valores.get(normalizarCodigoPractica(codigoPractica)) ?? 0
}

function precioFicticioMedicacion(nombre: string): number {
    const base = nombre.trim().length || 1
    return 3500 + (base % 15) * 180
}

function tieneNumeroAutorizacionValido(numeroAutorizacion: string | null | undefined): boolean {
    return typeof numeroAutorizacion === 'string' && numeroAutorizacion.trim().length > 0
}

function resolverNumeroAutorizacion(
    numeroAutorizacionItem: string | null | undefined,
    numeroAutorizacionOrden: string | null | undefined
): string | null {
    if (tieneNumeroAutorizacionValido(numeroAutorizacionItem)) return numeroAutorizacionItem!.trim()
    if (tieneNumeroAutorizacionValido(numeroAutorizacionOrden)) return numeroAutorizacionOrden!.trim()
    return null
}

function generarCodigoBarrasOrdenItem(puestoNumero: number, ordenNumero: number, item: number): string {
    return `${puestoNumero.toString().padStart(4, '0')}${ordenNumero.toString().padStart(8, '0')}${item.toString().padStart(3, '0')}`
}

function resolverNumeroAutorizacionOrdenItem(
    numeroAutorizacionItem: string | null | undefined,
    numeroAutorizacionOrden: string | null | undefined,
    puestoNumero: number,
    ordenNumero: number,
    item: number
): string | null {
    const authItem = numeroAutorizacionItem?.trim() ?? null
    const authOrden = numeroAutorizacionOrden?.trim() ?? null
    const codigoBarrasGenerado = generarCodigoBarrasOrdenItem(puestoNumero, ordenNumero, item)

    // If the item auth is only the autogenerated barcode, prefer the real order auth.
    if (authItem && authItem === codigoBarrasGenerado && tieneNumeroAutorizacionValido(authOrden)) {
        return authOrden
    }

    return resolverNumeroAutorizacion(authItem, authOrden)
}

function periodoToDateRange(periodo: string): { desde: Date; hasta: Date } {
    const [yearStr, monthStr] = periodo.split('-')
    const year = Number(yearStr)
    const month = Number(monthStr)
    const desde = new Date(Date.UTC(year, month - 1, 1, 0, 0, 0, 0))
    const hasta = new Date(Date.UTC(year, month, 1, 0, 0, 0, 0))
    return { desde, hasta }
}

export async function buscarAdmisionesFacturacion(
    params: BusquedaFacturacionInput
): Promise<{ items: AdmisionFacturacionListItem[]; total: number }> {
    const { q, tipoIngresoCodigo, codigoPractica, pagina, porPagina } = params
    const skip = (pagina - 1) * porPagina

    const where: Prisma.IngresoWhereInput = {
        estado: { in: ['A', 'E'] },
    }

    if (tipoIngresoCodigo) where.tipoIngresoCodigo = tipoIngresoCodigo

    if (q) {
        const esNumerico = /^\d+$/.test(q)
        if (esNumerico) {
            const n = parseInt(q, 10)
            where.OR = [
                { numeroIngreso: n },
                { paciente: { numeroDocumento: n } },
                { nombre: { contains: q, mode: 'insensitive' } },
            ]
        } else {
            where.OR = [
                { nombre: { contains: q, mode: 'insensitive' } },
                { paciente: { nombreCompleto: { contains: q, mode: 'insensitive' } } },
            ]
        }
    }

    if (codigoPractica) {
        where.AND = [
            {
                OR: [
                    { practicas: { some: { codigoPractica: { contains: codigoPractica, mode: 'insensitive' } } } },
                    {
                        ordenes: {
                            some: {
                                items: { some: { codigoPractica: { contains: codigoPractica, mode: 'insensitive' } } },
                            },
                        },
                    },
                ],
            },
        ]
    }

    const [total, items] = await prisma.$transaction([
        prisma.ingreso.count({ where }),
        prisma.ingreso.findMany({
            where,
            skip,
            take: porPagina,
            orderBy: [{ fechaIngreso: 'desc' }, { id: 'desc' }],
            select: {
                id: true,
                tipoIngresoCodigo: true,
                numeroIngreso: true,
                estado: true,
                fechaIngreso: true,
                fechaEgreso: true,
                paciente: {
                    select: {
                        id: true,
                        nombreCompleto: true,
                        numeroDocumento: true,
                    },
                },
                obraSocial: { select: { id: true, nombre: true } },
                plan: { select: { id: true, descripcion: true } },
            },
        }),
    ])

    return { items: items as AdmisionFacturacionListItem[], total }
}

export async function obtenerContextoFacturacion(ingresoId: number): Promise<FacturacionContexto | null> {
    const ingreso = await prisma.ingreso.findUnique({
        where: { id: ingresoId },
        select: {
            id: true,
            camaId: true,
            tipoIngresoCodigo: true,
            numeroIngreso: true,
            estado: true,
            fechaIngreso: true,
            fechaEgreso: true,
            nombre: true,
            descripcionPatologia: true,
            numeroAfiliado: true,
            observaciones: true,
            obraSocialId: true,
            planId: true,
            obraSocialCoseguroId: true,
            planCoseguroId: true,
            paciente: {
                select: {
                    id: true,
                    apellido: true,
                    nombre: true,
                    nombreCompleto: true,
                    numeroDocumento: true,
                    celular1: true,
                    email: true,
                    domicilio: true,
                },
            },
            obraSocial: { select: { id: true, nombre: true } },
            plan: { select: { id: true, descripcion: true } },
            practicas: {
                orderBy: [{ fecha: 'desc' }, { id: 'desc' }],
                select: {
                    id: true,
                    fecha: true,
                    codigoPractica: true,
                    cantidad: true,
                    convenioId: true,
                    numeroAutorizacion: true,
                    importeTotal: true,
                    puestoNumero: true,
                    ordenNumero: true,
                    ordenItem: true,
                    nomencladorPractica: { select: { descripcion: true } },
                },
            },
            medicaciones: {
                orderBy: [{ fechaInicio: 'desc' }, { id: 'desc' }],
                select: {
                    id: true,
                    fechaInicio: true,
                    nombre: true,
                    dosis: true,
                    viaAdministracion: true,
                    frecuencia: true,
                },
            },
            ordenes: {
                orderBy: [{ fechaEmision: 'desc' }, { numero: 'desc' }],
                select: {
                    puestoNumero: true,
                    numero: true,
                    estado: true,
                    numeroAutorizacion: true,
                    fechaEmision: true,
                    profesional: { select: { matricula: true } },
                    items: {
                        orderBy: { item: 'asc' },
                        select: {
                            item: true,
                            practicaId: true,
                            fecha: true,
                            convenioId: true,
                            codigoPractica: true,
                            cantidad: true,
                            numeroAutorizacion: true,
                            importeTotal: true,
                            nomencladorPractica: { select: { descripcion: true } },
                        },
                    },
                },
            },
        },
    })

    if (!ingreso) return null

    const reglaFacturacion = resolverReglaFacturacion(
        ingreso.obraSocial?.nombre,
        Boolean(ingreso.obraSocialCoseguroId)
    )

    const obraSocialCoseguro = ingreso.obraSocialCoseguroId
        ? await prisma.obraSocial.findUnique({
            where: { id: ingreso.obraSocialCoseguroId },
            select: { id: true, nombre: true },
        })
        : null

    const prestaciones: PrestacionFacturableItem[] = []
    const matriculaPorOrden = new Map<string, number | null>()
    const autorizacionPorOrden = new Map<string, string | null>()
    const autorizacionPorOrdenItem = new Map<string, string | null>()
    const puestoPorNumeroOrden = new Map<number, number>()
    const ordenVinculadaPorPractica = new Map<
        number,
        {
            puestoNumero: number
            numero: number
            item: number
            numeroAutorizacion: string | null
            estado: string | null
        }
    >()
    const practicasPendientesPorClave = new Map<
        string,
        Array<{ id: number; cantidad: number; fecha: Date }>
    >()
    const valoresPractica = await obtenerValoresPracticas(
        ingreso.practicas.map((p) => p.codigoPractica)
    )

    for (const p of ingreso.practicas) {
        if (p.ordenNumero) continue
        const clave = `${p.convenioId}:${normalizarCodigoPractica(p.codigoPractica)}:${Number(p.cantidad)}`
        const actuales = practicasPendientesPorClave.get(clave) ?? []
        actuales.push({ id: p.id, cantidad: Number(p.cantidad), fecha: p.fecha })
        practicasPendientesPorClave.set(clave, actuales)

        const claveCodigo = `${p.convenioId}:${normalizarCodigoPractica(p.codigoPractica)}:*`
        const actualesCodigo = practicasPendientesPorClave.get(claveCodigo) ?? []
        actualesCodigo.push({ id: p.id, cantidad: Number(p.cantidad), fecha: p.fecha })
        practicasPendientesPorClave.set(claveCodigo, actualesCodigo)
    }

    for (const o of ingreso.ordenes) {
        const claveOrden = `${o.puestoNumero}:${o.numero}`
        matriculaPorOrden.set(claveOrden, o.profesional?.matricula ?? null)
        autorizacionPorOrden.set(claveOrden, resolverNumeroAutorizacion(null, o.numeroAutorizacion))
        if (!puestoPorNumeroOrden.has(o.numero)) {
            puestoPorNumeroOrden.set(o.numero, o.puestoNumero)
        }
        for (const it of o.items) {
            autorizacionPorOrdenItem.set(
                `${o.puestoNumero}:${o.numero}:${it.item}`,
                resolverNumeroAutorizacionOrdenItem(
                    it.numeroAutorizacion,
                    o.numeroAutorizacion,
                    o.puestoNumero,
                    o.numero,
                    it.item
                )
            )

            let practicaIdAsociada = it.practicaId

            // Fallback legacy: when the order item is not linked via PraID,
            // try to pair with a single pending practice with same convenio/codigo/cantidad.
            if (!practicaIdAsociada) {
                const clave = `${it.convenioId}:${normalizarCodigoPractica(it.codigoPractica)}:${Number(it.cantidad)}`
                const claveCodigo = `${it.convenioId}:${normalizarCodigoPractica(it.codigoPractica)}:*`
                const candidatasExactas = practicasPendientesPorClave.get(clave) ?? []
                const candidatasCodigo = practicasPendientesPorClave.get(claveCodigo) ?? []

                const candidatas =
                    candidatasExactas.length > 0 ? candidatasExactas : candidatasCodigo

                if (candidatas.length > 0) {
                    const ordenadas = [...candidatas].sort((a, b) => {
                        const penalidadCantidadA = a.cantidad === Number(it.cantidad) ? 0 : 1
                        const penalidadCantidadB = b.cantidad === Number(it.cantidad) ? 0 : 1
                        if (penalidadCantidadA !== penalidadCantidadB) {
                            return penalidadCantidadA - penalidadCantidadB
                        }
                        const diffA = Math.abs(a.fecha.getTime() - it.fecha.getTime())
                        const diffB = Math.abs(b.fecha.getTime() - it.fecha.getTime())
                        return diffA - diffB
                    })
                    const mejor = ordenadas[0]
                    practicaIdAsociada = mejor?.id

                    if (mejor) {
                        practicasPendientesPorClave.set(
                            clave,
                            (practicasPendientesPorClave.get(clave) ?? []).filter((c) => c.id !== mejor.id)
                        )
                        practicasPendientesPorClave.set(
                            claveCodigo,
                            (practicasPendientesPorClave.get(claveCodigo) ?? []).filter((c) => c.id !== mejor.id)
                        )
                    }
                }
            }

            if (!practicaIdAsociada) continue

            ordenVinculadaPorPractica.set(practicaIdAsociada, {
                puestoNumero: o.puestoNumero,
                numero: o.numero,
                item: it.item,
                numeroAutorizacion: resolverNumeroAutorizacionOrdenItem(
                    it.numeroAutorizacion,
                    o.numeroAutorizacion,
                    o.puestoNumero,
                    o.numero,
                    it.item
                ),
                estado: o.estado,
            })
        }
    }

    for (const p of ingreso.practicas) {
        const vinculoPorItem = ordenVinculadaPorPractica.get(p.id)
        const tieneVinculoExplicitoEnDB = Boolean(p.ordenNumero || p.puestoNumero)
        const ordenPuestoNumero =
            p.puestoNumero ??
            vinculoPorItem?.puestoNumero ??
            (p.ordenNumero ? (puestoPorNumeroOrden.get(p.ordenNumero) ?? null) : null)
        const ordenNumero = p.ordenNumero ?? vinculoPorItem?.numero ?? null
        const ordenItem = p.ordenItem ?? vinculoPorItem?.item ?? null
        const claveOrden =
            ordenPuestoNumero && ordenNumero ? `${ordenPuestoNumero}:${ordenNumero}` : null
        const claveOrdenItem =
            ordenPuestoNumero && ordenNumero && ordenItem
                ? `${ordenPuestoNumero}:${ordenNumero}:${ordenItem}`
                : null
        const ordenVinculadaActiva = vinculoPorItem ? vinculoPorItem.estado !== 'X' : false
        const matriculaProfesional =
            ordenPuestoNumero && ordenNumero
                ? (matriculaPorOrden.get(`${ordenPuestoNumero}:${ordenNumero}`) ?? null)
                : null

        const precioNomenclador = valoresPractica.get(normalizarCodigoPractica(p.codigoPractica)) ?? 0
        const cobertura = calcularImporteFacturable(
            precioNomenclador,
            Number(p.cantidad),
            reglaFacturacion
        )
        const importeFromDb = p.importeTotal != null ? Number(String(p.importeTotal)) : null
        const cant = Number(p.cantidad)
        const precioUnitario = cobertura.precioUnitarioFacturable > 0
            ? cobertura.precioUnitarioFacturable
            : (importeFromDb !== null && cant > 0 ? importeFromDb / cant : cobertura.precioUnitarioFacturable)
        prestaciones.push({
            uid: `PRACTICA:${p.id}`,
            tipo: 'PRACTICA',
            referencia: `PRA-${p.id}`,
            fecha: p.fecha,
            descripcion: p.nomencladorPractica?.descripcion ?? p.codigoPractica.trim(),
            cantidad: cant,
            precioUnitario,
            importeTotal: importeFromDb ?? cobertura.importeTotalFacturable,
            facturada: Boolean(p.ordenNumero) || (Boolean(vinculoPorItem) && ordenVinculadaActiva),
            matriculaProfesional,
            ordenPuestoNumero,
            ordenNumero,
            convenioId: p.convenioId,
            codigoPractica: p.codigoPractica.trim(),
            numeroAutorizacion: tieneVinculoExplicitoEnDB
                ? resolverNumeroAutorizacion(
                    p.numeroAutorizacion,
                    resolverNumeroAutorizacion(
                        vinculoPorItem?.numeroAutorizacion,
                        resolverNumeroAutorizacion(
                            claveOrdenItem ? autorizacionPorOrdenItem.get(claveOrdenItem) : null,
                            claveOrden ? autorizacionPorOrden.get(claveOrden) : null
                        )
                    )
                )
                : (p.numeroAutorizacion?.trim() || null),
            origen: {
                ingresoId: ingreso.id,
                practicaId: p.id,
                ordenPuestoNumero: ordenPuestoNumero ?? undefined,
                ordenNumero: ordenNumero ?? undefined,
                ordenItem: ordenItem ?? undefined,
            },
        })
    }

    for (const o of ingreso.ordenes) {
        if (o.estado === 'X') continue
        for (const it of o.items) {
            const numeroAutorizacion = resolverNumeroAutorizacionOrdenItem(
                it.numeroAutorizacion,
                o.numeroAutorizacion,
                o.puestoNumero,
                o.numero,
                it.item
            )
            if (!tieneNumeroAutorizacionValido(numeroAutorizacion)) continue

            prestaciones.push({
                uid: `ORDEN_ITEM:${o.puestoNumero}:${o.numero}:${it.item}`,
                tipo: 'ORDEN_ITEM',
                referencia: `${o.puestoNumero.toString().padStart(4, '0')}-${o.numero.toString().padStart(8, '0')}-${it.item.toString().padStart(2, '0')}`,
                fecha: it.fecha,
                descripcion: it.nomencladorPractica?.descripcion ?? it.codigoPractica.trim(),
                cantidad: Number(it.cantidad),
                precioUnitario:
                    Number(it.cantidad) > 0
                        ? Number(String(it.importeTotal ?? 0)) / Number(it.cantidad)
                        : Number(String(it.importeTotal ?? 0)),
                importeTotal: Number(String(it.importeTotal ?? 0)),
                facturada: true,
                matriculaProfesional: o.profesional?.matricula ?? null,
                ordenPuestoNumero: o.puestoNumero,
                ordenNumero: o.numero,
                convenioId: it.convenioId,
                codigoPractica: it.codigoPractica.trim(),
                numeroAutorizacion,
                origen: {
                    ingresoId: ingreso.id,
                    ordenPuestoNumero: o.puestoNumero,
                    ordenNumero: o.numero,
                    ordenItem: it.item,
                },
            })
        }
    }

    for (const m of ingreso.medicaciones) {
        const detalle = [m.dosis, m.viaAdministracion, m.frecuencia].filter(Boolean).join(' · ')
        prestaciones.push({
            uid: `MEDICACION:${m.id}`,
            tipo: 'MEDICACION',
            referencia: `MED-${m.id}`,
            fecha: m.fechaInicio,
            descripcion: detalle ? `${m.nombre} (${detalle})` : m.nombre,
            cantidad: 1,
            precioUnitario: precioFicticioMedicacion(m.nombre),
            importeTotal: precioFicticioMedicacion(m.nombre),
            facturada: false,
            matriculaProfesional: null,
            ordenPuestoNumero: null,
            ordenNumero: null,
            convenioId: null,
            codigoPractica: null,
            numeroAutorizacion: null,
            origen: { ingresoId: ingreso.id, medicacionId: m.id },
        })
    }

    if (ingreso.tipoIngresoCodigo === 'INT' && ingreso.fechaIngreso) {
        const desde = new Date(ingreso.fechaIngreso)
        const hasta = ingreso.fechaEgreso ? new Date(ingreso.fechaEgreso) : new Date()
        const diferenciaDias = Math.max(1, Math.ceil((hasta.getTime() - desde.getTime()) / MS_POR_DIA))

        prestaciones.push({
            uid: `DIA_INTERNACION:${ingreso.id}`,
            tipo: 'DIA_INTERNACION',
            referencia: `DIA-INT-${ingreso.id}`,
            fecha: desde,
            descripcion: `Dias de internacion (${diferenciaDias})`,
            cantidad: diferenciaDias,
            precioUnitario: null,
            importeTotal: null,
            facturada: false,
            matriculaProfesional: null,
            ordenPuestoNumero: null,
            ordenNumero: null,
            convenioId: null,
            codigoPractica: null,
            numeroAutorizacion: null,
            origen: { ingresoId: ingreso.id },
        })
    }

    prestaciones.sort((a, b) => b.fecha.getTime() - a.fecha.getTime())

    return {
        ingreso: {
            id: ingreso.id,
            tipoIngresoCodigo: ingreso.tipoIngresoCodigo,
            numeroIngreso: ingreso.numeroIngreso,
            estado: ingreso.estado,
            fechaIngreso: ingreso.fechaIngreso,
            fechaEgreso: ingreso.fechaEgreso,
            nombre: ingreso.nombre,
            descripcionPatologia: ingreso.descripcionPatologia,
            numeroAfiliado: ingreso.numeroAfiliado,
            observaciones: ingreso.observaciones,
            obraSocialId: ingreso.obraSocialId,
            planId: ingreso.planId,
            obraSocialCoseguroId: ingreso.obraSocialCoseguroId,
        },
        paciente: ingreso.paciente,
        obraSocial: ingreso.obraSocial,
        obraSocialCoseguro,
        plan: ingreso.plan,
        reglaFacturacion,
        prestaciones,
    }
}

export async function crearPracticaFacturacion(
    data: CrearPracticaFacturacionInput,
    usuario: string
): Promise<{ id: number }> {
    const codigo = data.codigoPractica.trim().slice(0, 8)
    const cantidad = Number(data.cantidad)
    const ingreso = await prisma.ingreso.findUnique({
        where: { id: data.ingresoId },
        select: {
            obraSocialId: true,
            planId: true,
            obraSocialCoseguroId: true,
            obraSocial: { select: { nombre: true } },
        },
    })

    if (!ingreso) throw new Error('Ingreso no encontrado')

    const regla = resolverReglaFacturacion(
        ingreso.obraSocial?.nombre,
        Boolean(ingreso.obraSocialCoseguroId)
    )
    const valorPractica = await obtenerValorPractica(codigo)
    const cobertura = calcularImporteFacturable(valorPractica, cantidad, regla)
    const importeTotal = cobertura.importeTotalFacturable

    const practica = await prisma.practica.create({
        data: {
            ingresoId: data.ingresoId,
            convenioId: data.convenioId,
            codigoPractica: codigo.padEnd(8, ' '),
            convenioValorId: 0,
            fecha: data.fecha,
            cantidad,
            numeroAutorizacion: data.numeroAutorizacion ?? null,
            obraSocialId: ingreso.obraSocialId ?? null,
            planId: ingreso.planId ?? null,
            facturable: true,
            importeTotal,
            usuarioRegistro: usuario.trim().slice(0, 10) || 'SISTEMA',
        },
        select: { id: true },
    })

    return practica
}

export async function crearMedicacionFacturacion(
    data: CrearMedicacionFacturacionInput,
    usuario: string
): Promise<{ id: number }> {
    const medicacion = await prisma.medicacionIngreso.create({
        data: {
            ingresoId: data.ingresoId,
            nombre: data.nombre,
            dosis: data.dosis ?? null,
            viaAdministracion: data.viaAdministracion ?? null,
            frecuencia: data.frecuencia ?? null,
            fechaInicio: data.fechaInicio,
            fechaFin: data.fechaFin ?? null,
            observaciones: data.observaciones ?? null,
            profesionalId: data.profesionalId ?? null,
            estado: 'A',
            usuario: usuario.trim().slice(0, 10) || 'SISTEMA',
            fechaEstado: new Date(),
        },
        select: { id: true },
    })

    return medicacion
}

export async function actualizarContextoFacturacion(
    ingresoId: number,
    data: ActualizarContextoFacturacionInput,
    usuario: string
): Promise<void> {
    await prisma.$transaction(async (tx) => {
        if (data.ingreso) {
            await tx.ingreso.update({
                where: { id: ingresoId },
                data: {
                    nombre: data.ingreso.nombre,
                    descripcionPatologia: data.ingreso.descripcionPatologia,
                    numeroAfiliado: data.ingreso.numeroAfiliado,
                    observaciones: data.ingreso.observaciones,
                    obraSocialId: data.ingreso.obraSocialId,
                    planId: data.ingreso.planId,
                    fechaEstado: new Date(),
                    usuario: usuario.trim().slice(0, 10) || 'SISTEMA',
                },
            })
        }

        if (data.paciente) {
            const ingreso = await tx.ingreso.findUnique({
                where: { id: ingresoId },
                select: { pacienteId: true },
            })

            if (ingreso?.pacienteId) {
                await tx.paciente.update({
                    where: { id: ingreso.pacienteId },
                    data: {
                        apellido: data.paciente.apellido,
                        nombre: data.paciente.nombre,
                        nombreCompleto: data.paciente.nombreCompleto,
                        numeroDocumento: data.paciente.numeroDocumento,
                        celular1: data.paciente.celular1,
                        email: data.paciente.email,
                        domicilio: data.paciente.domicilio,
                        fechaModificacion: new Date(),
                    },
                })
            }
        }
    })
}

export async function cargarOrdenesDesdePrestaciones(
    data: CargarOrdenesFacturacionInput,
    usuario: string
): Promise<OrdenFacturacionResultado> {
    const ingreso = await prisma.ingreso.findUnique({
        where: { id: data.ingresoId },
        select: {
            id: true,
            pacienteId: true,
            nombre: true,
            numeroAfiliado: true,
            obraSocialId: true,
            planId: true,
            obraSocialCoseguroId: true,
            planCoseguroId: true,
            descripcionPatologia: true,
            profesionalTratanteId: true,
            profesionalGuardiaId: true,
            obraSocial: { select: { nombre: true } },
        },
    })

    if (!ingreso) throw new Error('Ingreso no encontrado')
    if (!ingreso.obraSocialId) {
        throw new Error('El ingreso no tiene obra social cargada')
    }

    const profesionalId =
        data.profesionalId ?? ingreso.profesionalTratanteId ?? ingreso.profesionalGuardiaId
    if (!profesionalId) throw new Error('Debe indicar un profesional para generar la orden')

    let prestacionesOrigen = data.prestaciones
    // Track IDs of pending Practica records so we can back-link them after order creation
    let practicaIdsOrdenados: number[] = []

    if (data.facturarTodo || prestacionesOrigen.length === 0) {
        const practicasPendientes = await prisma.practica.findMany({
            where: {
                ingresoId: data.ingresoId,
                facturable: true,
                ordenNumero: null,
                AND: [
                    { numeroAutorizacion: { not: null } },
                    { numeroAutorizacion: { not: '' } },
                ],
            },
            orderBy: [{ fecha: 'asc' }, { id: 'asc' }],
            select: {
                id: true,
                convenioId: true,
                codigoPractica: true,
                cantidad: true,
                numeroAutorizacion: true,
                nomencladorPractica: { select: { descripcion: true } },
            },
        })

        practicaIdsOrdenados = practicasPendientes.map((p) => p.id)

        prestacionesOrigen = practicasPendientes.map((p) => ({
            convenioId: p.convenioId,
            codigoPractica: p.codigoPractica.trim(),
            descripcionPractica: p.nomencladorPractica?.descripcion ?? p.codigoPractica.trim(),
            cantidad: Number(p.cantidad),
            numeroAutorizacion: p.numeroAutorizacion,
        }))
    }

    prestacionesOrigen = prestacionesOrigen.map((p) => ({
        ...p,
        numeroAutorizacion:
            typeof p.numeroAutorizacion === 'string' ? p.numeroAutorizacion.trim() : p.numeroAutorizacion,
    }))

    const prestacionesSinAutorizacion = prestacionesOrigen.filter(
        (p) => !tieneNumeroAutorizacionValido(p.numeroAutorizacion)
    )
    if (prestacionesSinAutorizacion.length > 0) {
        throw new Error('No se puede facturar sin número de autorización. Confirmá la orden primero.')
    }

    if (prestacionesOrigen.length === 0) {
        throw new Error('No hay practicas pendientes para facturar en este ingreso')
    }

    const reglaFacturacion = resolverReglaFacturacion(
        ingreso.obraSocial?.nombre,
        Boolean(ingreso.obraSocialCoseguroId)
    )

    const ordenInput: CrearOrdenInput = {
        ingresoId: ingreso.id,
        pacienteId: ingreso.pacienteId ?? undefined,
        nombrePaciente: (ingreso.nombre ?? '').slice(0, 50) || 'SIN NOMBRE',
        numeroAfiliado: ingreso.numeroAfiliado ?? '',
        obraSocialId: ingreso.obraSocialId,
        planId: ingreso.planId,
        obraSocialCoseguroId: ingreso.obraSocialCoseguroId ?? undefined,
        planCoseguroId: ingreso.planCoseguroId ?? undefined,
        profesionalId,
        tipoOrdenCodigo: 'PRA',
        descripcionPatologia: ingreso.descripcionPatologia ?? undefined,
        items: await Promise.all(prestacionesOrigen.map(async (p) => {
            const codigo = p.codigoPractica.trim().slice(0, 8)
            const cantidad = Number(p.cantidad)
            const unitario = await obtenerValorPractica(codigo)
            const cobertura = calcularImporteFacturable(unitario, cantidad, reglaFacturacion)

            return {
                convenioId: p.convenioId,
                codigoPractica: codigo,
                descripcionPractica: p.descripcionPractica,
                cantidad,
                numeroAutorizacion: p.numeroAutorizacion?.trim() ?? null,
                tipoFacturacion: 'H',
                importeTotal: cobertura.importeTotalFacturable,
                porcentajeCargoPac:
                    cobertura.porcentajeCargoPaciente > 0
                        ? cobertura.porcentajeCargoPaciente
                        : undefined,
            }
        })),
    }

    if (data.modo === 'INDIVIDUAL') {
        const ordenes = await crearOrdenesAmbulatoriasPorPractica(ordenInput, usuario)
        // Back-link each Practica to its corresponding individual order (item 1 each)
        if (practicaIdsOrdenados.length > 0) {
            await Promise.all(
                practicaIdsOrdenados.map((practicaId, idx) => {
                    const ref = ordenes[idx]
                    if (!ref) return Promise.resolve()
                    return prisma.practica.update({
                        where: { id: practicaId },
                        data: {
                            puestoNumero: ref.puestoNumero,
                            ordenNumero: ref.numero,
                            ordenItem: 1,
                        },
                    })
                })
            )
        }
        return { modo: 'INDIVIDUAL', ordenes }
    }

    const orden = await crearOrdenAmbulatorio(ordenInput, usuario)
    // Back-link each Practica to the MASIVA order, preserving item order
    if (practicaIdsOrdenados.length > 0) {
        await Promise.all(
            practicaIdsOrdenados.map((practicaId, idx) =>
                prisma.practica.update({
                    where: { id: practicaId },
                    data: {
                        puestoNumero: orden.puestoNumero,
                        ordenNumero: orden.numero,
                        ordenItem: idx + 1,
                    },
                })
            )
        )
    }
    return {
        modo: 'MASIVA',
        ordenes: [{ puestoNumero: orden.puestoNumero, numero: orden.numero }],
    }
}

export async function actualizarNumeroAutorizacion(
    data: ActualizarAutorizacionInput
): Promise<void> {
    if (data.tipo === 'PRACTICA') {
        await prisma.practica.update({
            where: { id: data.practicaId },
            data: { numeroAutorizacion: data.numeroAutorizacion ?? null },
        })
        return
    }

    await prisma.ordenPractica.update({
        where: {
            puestoNumero_ordenNumero_item: {
                puestoNumero: data.puestoNumero,
                ordenNumero: data.ordenNumero,
                item: data.item,
            },
        },
        data: { numeroAutorizacion: data.numeroAutorizacion ?? null },
    })
}

async function resolverPracticaDesdeInput(
    codigoPractica: string,
    descripcionPractica: string | null | undefined,
    convenioIdActual: number
): Promise<{ convenioId: number; codigoPractica: string }> {
    const codigo = codigoPractica.trim().slice(0, 8)
    const exacto = await prisma.nomencladorPractica.findFirst({
        where: {
            convenioId: convenioIdActual,
            codigo: { startsWith: codigo },
        },
        select: { convenioId: true, codigo: true },
    })
    if (exacto) return { convenioId: exacto.convenioId, codigoPractica: exacto.codigo.trim() }

    if (descripcionPractica?.trim()) {
        const porDescripcion = await prisma.nomencladorPractica.findFirst({
            where: { descripcion: { contains: descripcionPractica.trim(), mode: 'insensitive' } },
            select: { convenioId: true, codigo: true },
            orderBy: [{ convenioId: 'asc' }, { codigo: 'asc' }],
        })
        if (porDescripcion) {
            return { convenioId: porDescripcion.convenioId, codigoPractica: porDescripcion.codigo.trim() }
        }
    }

    return { convenioId: convenioIdActual, codigoPractica: codigo }
}

export async function actualizarPrestacionFacturacion(
    data: ActualizarPrestacionFacturacionInput
): Promise<void> {
    if (data.tipo === 'PRACTICA') {
        const actual = await prisma.practica.findUnique({
            where: { id: data.practicaId },
            select: { convenioId: true },
        })
        if (!actual) throw new Error('Práctica no encontrada')

        const resolved = await resolverPracticaDesdeInput(
            data.codigoPractica,
            data.descripcionPractica,
            actual.convenioId
        )

        await prisma.practica.update({
            where: { id: data.practicaId },
            data: {
                fecha: data.fecha,
                convenioId: resolved.convenioId,
                codigoPractica: resolved.codigoPractica.padEnd(8, ' '),
                cantidad: data.cantidad,
                numeroAutorizacion: data.numeroAutorizacion ?? null,
                importeTotal: data.importeTotal,
                // Unlink from any existing order so it's treated as pending again
                puestoNumero: null,
                ordenNumero: null,
                ordenItem: null,
            },
        })
        return
    }

    const actualItem = await prisma.ordenPractica.findUnique({
        where: {
            puestoNumero_ordenNumero_item: {
                puestoNumero: data.puestoNumero,
                ordenNumero: data.ordenNumero,
                item: data.item,
            },
        },
        select: { convenioId: true },
    })
    if (!actualItem) throw new Error('Ítem de orden no encontrado')

    const resolved = await resolverPracticaDesdeInput(
        data.codigoPractica,
        data.descripcionPractica,
        actualItem.convenioId
    )

    await prisma.ordenPractica.update({
        where: {
            puestoNumero_ordenNumero_item: {
                puestoNumero: data.puestoNumero,
                ordenNumero: data.ordenNumero,
                item: data.item,
            },
        },
        data: {
            fecha: data.fecha,
            convenioId: resolved.convenioId,
            codigoPractica: resolved.codigoPractica.padEnd(8, ' '),
            cantidad: data.cantidad,
            numeroAutorizacion: data.numeroAutorizacion ?? null,
            importeTotal: data.importeTotal,
        },
    })

    if (data.matriculaProfesional) {
        const profesional = await prisma.profesional.findFirst({
            where: { matricula: data.matriculaProfesional },
            select: { id: true },
        })
        if (profesional) {
            await prisma.orden.update({
                where: {
                    puestoNumero_numero: {
                        puestoNumero: data.puestoNumero,
                        numero: data.ordenNumero,
                    },
                },
                data: { profesionalId: profesional.id },
            })
        }
    }

    const orden = await prisma.orden.findUnique({
        where: { puestoNumero_numero: { puestoNumero: data.puestoNumero, numero: data.ordenNumero } },
        select: { items: { select: { importeTotal: true } } },
    })
    if (orden) {
        const total = orden.items.reduce((sum, it) => sum + Number(it.importeTotal ?? 0), 0)
        await prisma.orden.update({
            where: { puestoNumero_numero: { puestoNumero: data.puestoNumero, numero: data.ordenNumero } },
            data: { importeTotal: total },
        })
    }
}

export async function anularOrdenFacturacion(puestoNumero: number, numero: number): Promise<void> {
    await prisma.$transaction(async (tx) => {
        // Unlink Practica records that were source of this order
        await tx.practica.updateMany({
            where: { puestoNumero, ordenNumero: numero },
            data: { puestoNumero: null, ordenNumero: null, ordenItem: null },
        })
        // Cancel the order
        await tx.orden.update({
            where: { puestoNumero_numero: { puestoNumero, numero } },
            data: { estado: 'X', fechaEstado: new Date() },
        })
    })
}

// ============================================
// LOTES DE FACTURACIÓN
// ============================================

const LOTE_SELECT = {
    id: true,
    numero: true,
    fecha: true,
    periodo: true,
    tipo: true,
    estado: true,
    sedeId: true,
    descripcion: true,
    concepto: true,
    importeTotal: true,
    tipoIngresoCodigo: true,
    rangoDesde: true,
    rangoHasta: true,
    obraSocial: { select: { id: true, nombre: true } },
    plan: { select: { id: true, descripcion: true } },
} satisfies Prisma.LoteFacturacionSelect

function mapLoteRow(row: Awaited<ReturnType<typeof prisma.loteFacturacion.findFirst>>): LoteFacturacionListItem {
    if (!row) throw new Error('Lote no encontrado')
    return {
        ...row,
        tipo: row.tipo as LoteFacturacionListItem['tipo'],
        estado: row.estado as EstadoLote,
        importeTotal: Number(row.importeTotal),
    }
}

export async function buscarLotes(
    params: BusquedaLotesInput
): Promise<{ items: LoteFacturacionListItem[]; total: number }> {
    const { periodo, estado, obraSocialId, tipo, pagina, porPagina } = params
    const skip = (pagina - 1) * porPagina

    const where: Prisma.LoteFacturacionWhereInput = {}
    if (periodo) where.periodo = periodo
    if (estado) where.estado = estado
    if (obraSocialId) where.obraSocialId = obraSocialId
    if (tipo) where.tipo = tipo

    const [total, rows] = await prisma.$transaction([
        prisma.loteFacturacion.count({ where }),
        prisma.loteFacturacion.findMany({
            where,
            skip,
            take: porPagina,
            orderBy: [{ fecha: 'desc' }, { id: 'desc' }],
            select: LOTE_SELECT,
        }),
    ])

    return { items: rows.map(mapLoteRow), total }
}

export async function obtenerLote(id: number): Promise<LoteFacturacionDetalle | null> {
    const lote = await prisma.loteFacturacion.findUnique({
        where: { id },
        select: {
            ...LOTE_SELECT,
            items: {
                orderBy: [{ ingreso: { fechaIngreso: 'asc' } }, { id: 'asc' }],
                select: {
                    id: true,
                    loteId: true,
                    ingresoId: true,
                    incluido: true,
                    importeTotal: true,
                    ingreso: {
                        select: {
                            id: true,
                            tipoIngresoCodigo: true,
                            numeroIngreso: true,
                            estado: true,
                            fechaIngreso: true,
                            fechaEgreso: true,
                            nombre: true,
                            numeroAfiliado: true,
                            descripcionPatologia: true,
                            paciente: { select: { id: true, nombreCompleto: true, numeroDocumento: true } },
                        },
                    },
                },
            },
        },
    })

    if (!lote) return null

    return {
        ...mapLoteRow(lote),
        items: lote.items.map((item) => ({
            ...item,
            importeTotal: Number(item.importeTotal),
            paciente: item.ingreso.paciente,
        })) as LoteFacturacionItemDetalle[],
    }
}

export async function crearLote(
    data: CrearLoteFacturacionInput,
    usuario: string
): Promise<{ id: number; numero: number }> {
    const now = new Date()
    const usuarioCod = usuario.trim().slice(0, 10) || 'SISTEMA'

    // Determine next numero
    const ultimo = await prisma.loteFacturacion.findFirst({
        orderBy: { numero: 'desc' },
        select: { numero: true },
    })
    const numero = (ultimo?.numero ?? 0) + 1
    const { desde, hasta } = periodoToDateRange(data.periodo)

    // Build where for ingreso resolution
    const whereIngreso: Prisma.IngresoWhereInput = {
        estado: { in: ['A', 'E'] },
    }
    if (data.tipoIngresoCodigo) whereIngreso.tipoIngresoCodigo = data.tipoIngresoCodigo
    if (data.clienteTipo === 'PARTICULAR') {
        whereIngreso.obraSocialId = null
    } else {
        if (!data.obraSocialId) {
            throw new Error('Debe seleccionar una obra social cuando el cliente es obra social')
        }
        whereIngreso.obraSocialId = data.obraSocialId
    }
    if (data.rangoDesde || data.rangoHasta) {
        whereIngreso.numeroIngreso = {
            ...(data.rangoDesde ? { gte: data.rangoDesde } : {}),
            ...(data.rangoHasta ? { lte: data.rangoHasta } : {}),
        }
    }
    // If no obraSocialId, could be particular (no OS). If obraSocialId is set, filter by it.

    // Filter ingresos that have at least one authorized prestacion of the right type
    if (data.tipo === 'PRACTICAS') {
        whereIngreso.ordenes = {
            some: {
                estado: { not: 'X' },
                fechaEmision: { gte: desde, lt: hasta },
                OR: [
                    {
                        AND: [
                            { numeroAutorizacion: { not: null } },
                            { numeroAutorizacion: { not: '' } },
                        ],
                    },
                    {
                        items: {
                            some: {
                                AND: [
                                    { numeroAutorizacion: { not: null } },
                                    { numeroAutorizacion: { not: '' } },
                                ],
                            },
                        },
                    },
                ],
            },
        }
    } else {
        whereIngreso.medicaciones = {
            some: {
                estado: { not: 'S' },
                fechaInicio: { gte: desde, lt: hasta },
            },
        }
    }

    const ingresos = await prisma.ingreso.findMany({
        where: whereIngreso,
        select: {
            id: true,
            ordenes: data.tipo === 'PRACTICAS'
                ? {
                    where: { estado: { not: 'X' }, fechaEmision: { gte: desde, lt: hasta } },
                    select: {
                        numeroAutorizacion: true,
                        items: {
                            select: { importeTotal: true, numeroAutorizacion: true },
                        },
                    },
                }
                : false,
            medicaciones: data.tipo === 'MEDICAMENTOS'
                ? {
                    where: { estado: { not: 'S' }, fechaInicio: { gte: desde, lt: hasta } },
                    select: { nombre: true },
                }
                : false,
        },
    })

    // Compute importe per ingreso
    const itemsData = ingresos.map((ing) => {
        let importe = 0
        if (data.tipo === 'PRACTICAS' && ing.ordenes) {
            const ordenes = ing.ordenes as unknown as Array<{
                numeroAutorizacion: string | null
                items: Array<{ importeTotal: unknown; numeroAutorizacion: string | null }>
            }>

            const itemsAutorizados = ordenes.flatMap((o) => {
                const ordenConAutorizacion = tieneNumeroAutorizacionValido(o.numeroAutorizacion)
                return o.items.filter((it) =>
                    ordenConAutorizacion || tieneNumeroAutorizacionValido(it.numeroAutorizacion)
                )
            })

            importe += itemsAutorizados
                .reduce((s: number, i) => s + Number(i.importeTotal ?? 0), 0)
        }
        if (data.tipo === 'MEDICAMENTOS' && ing.medicaciones) {
            importe += (ing.medicaciones as Array<{ nombre: string }>).reduce(
                (s, m) => s + precioFicticioMedicacion(m.nombre),
                0
            )
        }
        return { ingresoId: ing.id, importeTotal: importe, incluido: true }
    })

    const totalLote = itemsData.reduce((s, it) => s + it.importeTotal, 0)

    const lote = await prisma.loteFacturacion.create({
        data: {
            numero,
            fecha: data.fecha,
            periodo: data.periodo,
            tipo: data.tipo,
            obraSocialId: data.obraSocialId ?? null,
            planId: data.planId ?? null,
            tipoIngresoCodigo: data.tipoIngresoCodigo ?? null,
            rangoDesde: data.rangoDesde ?? null,
            rangoHasta: data.rangoHasta ?? null,
            sedeId: data.sedeId ?? null,
            descripcion: data.descripcion ?? null,
            concepto: data.concepto ?? null,
            importeTotal: totalLote,
            estado: 'PEN',
            fechaEstado: now,
            usuario: usuarioCod,
            items: { create: itemsData },
        },
        select: { id: true, numero: true },
    })

    return lote
}

export async function actualizarLote(
    id: number,
    data: ActualizarLoteFacturacionInput,
    usuario: string
): Promise<void> {
    const usuarioCod = usuario.trim().slice(0, 10) || 'SISTEMA'
    const result = await prisma.loteFacturacion.updateMany({
        where: { id, estado: 'PEN' },
        data: {
            fecha: data.fecha,
            periodo: data.periodo,
            tipoIngresoCodigo: data.tipoIngresoCodigo,
            descripcion: data.descripcion,
            concepto: data.concepto,
            sedeId: data.sedeId,
            rangoDesde: data.rangoDesde,
            rangoHasta: data.rangoHasta,
            fechaEstado: new Date(),
            usuario: usuarioCod,
        },
    })

    if (result.count === 0) {
        throw new Error('Solo se puede editar un lote pendiente')
    }
}

export async function cambiarEstadoLote(
    id: number,
    estado: 'CON' | 'ANU',
    usuario: string
): Promise<void> {
    const usuarioCod = usuario.trim().slice(0, 10) || 'SISTEMA'
    await prisma.loteFacturacion.update({
        where: { id },
        data: { estado, fechaEstado: new Date(), usuario: usuarioCod },
    })
}

export async function toggleItemLote(
    loteId: number,
    itemId: number,
    incluido: boolean
): Promise<void> {
    // Only allow toggle when lote is PEN
    const lote = await prisma.loteFacturacion.findUnique({ where: { id: loteId }, select: { estado: true } })
    if (!lote || lote.estado !== 'PEN') throw new Error('Solo se puede editar un lote pendiente')

    const updated = await prisma.loteFacturacionItem.updateMany({
        where: { id: itemId, loteId },
        data: { incluido },
    })

    if (updated.count === 0) throw new Error('Item de lote no encontrado')

    // Recompute importeTotal of the lote
    const items = await prisma.loteFacturacionItem.findMany({
        where: { loteId, incluido: true },
        select: { importeTotal: true },
    })
    const total = items.reduce((s, it) => s + Number(it.importeTotal), 0)
    await prisma.loteFacturacion.update({ where: { id: loteId }, data: { importeTotal: total } })
}

export async function obtenerOrdenesAutorizadasIngreso(ingresoId: number): Promise<OrdenAutorizadaLote[]> {
    const ordenes = await prisma.orden.findMany({
        where: {
            ingresoId,
            estado: { not: 'X' },
            OR: [
                {
                    AND: [
                        { numeroAutorizacion: { not: null } },
                        { numeroAutorizacion: { not: '' } },
                    ],
                },
                {
                    items: {
                        some: {
                            AND: [
                                { numeroAutorizacion: { not: null } },
                                { numeroAutorizacion: { not: '' } },
                            ],
                        },
                    },
                },
            ],
        },
        orderBy: { fechaEmision: 'asc' },
        select: {
            puestoNumero: true,
            numero: true,
            fechaEmision: true,
            descripcion: true,
            numeroAutorizacion: true,
            importeTotal: true,
            items: {
                select: {
                    item: true,
                    codigoPractica: true,
                    cantidad: true,
                    numeroAutorizacion: true,
                    importeTotal: true,
                    nomencladorPractica: { select: { descripcion: true } },
                },
            },
        },
    })

    return ordenes.map((o) => ({
        puestoNumero: o.puestoNumero,
        numero: o.numero,
        fechaEmision: o.fechaEmision,
        descripcion: o.descripcion,
        numeroAutorizacion: o.numeroAutorizacion,
        importeTotal: Number(o.importeTotal ?? 0),
        items: o.items
            .filter(
                (it) =>
                    tieneNumeroAutorizacionValido(
                        resolverNumeroAutorizacion(it.numeroAutorizacion, o.numeroAutorizacion)
                    )
            )
            .map((it) => ({
                item: it.item,
                codigoPractica: it.codigoPractica,
                descripcion: it.nomencladorPractica?.descripcion ?? null,
                cantidad: Number(it.cantidad),
                numeroAutorizacion: resolverNumeroAutorizacion(it.numeroAutorizacion, o.numeroAutorizacion),
                importeTotal: Number(it.importeTotal ?? 0),
            })),
    }))
}
