// Auto-generated fallback catalog from existencia.xlsx and LISTADO MEDICACION.xlsx
// Regenerate when source files change.
export const INSUMOS_UTI_FALLBACK: string[] = [
  "ABBOCATH N° 14",
  "ABBOCATH N° 16",
  "ABBOCATH N° 18",
  "ABBOCATH N° 20",
  "ABBOCATH N° 22",
  "ABBOCATH N° 24",
  "Abocatt N° 14",
  "Abocatt N° 16",
  "Abocatt N° 18",
  "Abocatt N° 20",
  "Abocatt N° 22",
  "Abocatt N°24",
  "Acenocumarol 4 mg",
  "ACENOCUMAROL 4 MG COMPRIMIDOS",
  "ACETAZOLAMIDA 250 MG COMPRIMIDOS",
  "ACETILCISTEINA 600 MG EFERV.",
  "ACICLOVIR 500 MG FA",
  "ACICLOVIR 800MG COMP.",
  "ACIDO ACETILSALICILICO 100MG COMP",
  "ACIDO AMINOCAPROICO 2 G/10 ML AMPOLLA",
  "Acido folico 10 mg",
  "Acido folico 5 mg",
  "ACIDO FOLICO COMP",
  "Acido Poliglicolico N° 2",
  "Acido Tranexamico 500 mg",
  "ACIDO TRANEXAMICO 500 MG/5 ML AMPOLLA",
  "ADENOSINA 3 MG/2 ML AMPOLLA",
  "ADHESOL FCO",
  "Adrenalina 1 mg",
  "ADRENALINA 1 MG/1 ML AMPOLLA",
  "Agua destilada 500",
  "AGUA DESTILADA X 2000 ML SACHET",
  "AGUA DESTILADA X 500 ML SACHET",
  "Agua oxigenada 10 vol. Fco 1 lt.",
  "AGUA OXIGENADA 10 VOL. X 1 LT.",
  "AGUA OXIGENADA 5LTS",
  "AGUJA 13/4",
  "AGUJA 16/5",
  "AGUJA 25/8",
  "AGUJA 40/12",
  "AGUJA 40/8",
  "Aguja 50 x 12 mm ecorrefungante anestesia regional",
  "AGUJA 50/12",
  "AGUJA 50/8",
  "Aguja bloqueo N°22 G 7x50 mm",
  "AGUJA ESPINAL 21G",
  "AGUJA ESPINAL 22G X 3 1/2",
  "AGUJA ESPINAL 25GX 3 1/2",
  "AGUJA ESPINAL 26G X 3 1/2",
  "AGUJA ESPINAL 27 X 5",
  "AGUJA ESPINAL 27G X 3 1/2",
  "Aguja G25 punto lapiz",
  "Aguja G26 punto lapiz",
  "Aguja G27 punto lapiz",
  "AGUJA P/BLOQ. NERVIOSO 0.50 100MM STIMUPLEX",
  "AGUJA PARA LAPICERA INSULINA",
  "ALBUMINA HUMANA FCO.X 50 ML",
  "ALCOHOL 70º X 1LT",
  "ALCOHOL 96% BIDON 5LTS",
  "ALCOHOL 96% X 1LT",
  "ALCOHOL EN GEL 1LT",
  "ALCOHOL EN GEL 5LT",
  "ALCOHOL IODADO 1 LITRO",
  "Alfa metildopa 500 mg",
  "ALGODON X 500 GRS",
  "ALLOPURINOL 300 MG COMPRIMIDOS",
  "ALPRAZOLAM 0.5 MG COMPRIMIDOS",
  "ALPRAZOLAM 1 MG COMPRIMIDOS",
  "Alprazolan 0,5 mg",
  "Alprazolan 1 mg",
  "Alprazolan 2 mg",
  "Amikacina 500 mg",
  "AMIKACINA 500 MG/2 ML AMPOLLA",
  "AMINOFILINA 240 MG AMP",
  "Amiodarona 150 mg",
  "AMIODARONA 150 MG/3 ML AMPOLLA",
  "Amiodarona 200 mg",
  "AMIODARONA 200 MG COMPRIMIDOS",
  "Amlodipina 10 mg",
  "AMLODIPINA 10 MG COMPRIMIDOS",
  "Amlodipina 5 mg",
  "AMLODIPINA 5 MG COMPRIMIDOS",
  "AMOXICILINA + CLAVULANICO COMP",
  "AMOXICILINA 500 MG COMPRIMIDOS",
  "Amoxidal Duo 500 mg",
  "Amoxidal-Duo 1 gr",
  "Amoxidal-Duo 875/125 mg",
  "AMPICILINA 1 G FA",
  "Ampicilina 1 gr",
  "Ampicilina Sulbactam 1,5 mg",
  "AMPICILINA+SULBACTAM 1,5 G FA",
  "APARATO HGT",
  "APOSITO TEGADERM 10X 12CM",
  "APOSITO TEGADERM 15X19",
  "APOSITO TEGADERM 15X20",
  "APOSITO TEGADERM 6X7CM",
  "Aspirina 100 mg",
  "Atorvastatina 10 mg",
  "ATORVASTATINA 10 MG COMPRIMIDOS",
  "Atorvastatina 20 mg",
  "ATORVASTATINA 20MG COMP",
  "Atorvastatina 40 mg",
  "ATORVASTATINA 40 MG COMPRIMIDOS",
  "ATRACURIO 50 MG/5 ML AMPOLLA",
  "Atracurio 50mg/5 ml",
  "ATROPINA 1 %/1 ML AMPOLLA",
  "Atropina 1 mg",
  "AZITROMICINA 500 MG COMPRIMIDOS",
  "Bactrim 400/80mg",
  "BAJALENGUA ADULTOS",
  "BARBIJOS N95",
  "BARBIJOS N96",
  "BARBIJOS QUIRUGICOS",
  "BAREX BIDÓN",
  "Barex Poli etilenglicol 3350 fco 4 ltr",
  "BAREX SOBRES",
  "BECOZYM AMPOLLA",
  "Becozyn NF 2 ml",
  "Bicarbonato de Sodio Molar 200 mg/100 ml (sachet)",
  "Bisoprolol 10 mg",
  "Bisoprolol 2,5 mg",
  "Bisoprolol 5 mg",
  "BISOPROLOL 5 MG COMPRIMIDOS",
  "Bolsa colectomia con desagote y aro siliconado",
  "Bolsa colectora",
  "BOLSA COLECTORA DE ORINA 2 LT. C/GANCHO",
  "BOLSA PARA COLOSTOMIA COMÚN",
  "BOLSA PARA COLOSTOMÍA CON DESAGOTE",
  "BOLSA PARA COLOSTOMIA DE TELA",
  "BOTAS CUBRE CALZADOS",
  "Bromhexina Clorhidrato fco 120 ml",
  "BROMHEXINA JBE",
  "Bromuro de Ipratropio 20 ml (gotas)",
  "Bromuro de Ipratropio 20mcg/dosis",
  "BROMURO DE IPRATROPIO AEROSOL X PUFF",
  "BROMURO DE IPRATROPIO GOTAS",
  "Bromuro de Pancuronio 4 mg",
  "BROMURO DE PANCURONIO 4 MG/2 ML AMPOLLA",
  "Budesonida 20 ml (gotas)",
  "Budesonida 200 mcg/dosis",
  "BUDESONIDE 20 ML GOTAS",
  "BUDESONIDE AEROSOL",
  "BUPIVACAINA HIPERBARICA 0.50% a.x 4 ml",
  "Bupivacaina Hiperbarica 5mg/ml",
  "Bupivacaina Isotonica 0,5 mg/ml fco 20 ml s/E",
  "BUPIVACAINA SIN EPINEFRINA 20 ML FA",
  "CAL SODADA GRANULADA X 1 KGR.",
  "CAMISOLIN",
  "CANULA DE ASPIRACION 66",
  "CANULA DE ASPIRACION 67",
  "CANULA DE TRAQUEOSTOMIA N° 7",
  "Canula nasal",
  "CANULA NASAL K27",
  "CANULA TRAQUEAL N° 7",
  "CANULA TRAQUEAL N° 7 C/ ASP. SUBGLIOTICA",
  "CANULA TRAQUEAL N° 7,5",
  "CANULA TRAQUEAL N° 7.5 C/ ASP. SUBGLIOTICA",
  "CANULA TRAQUEAL N° 8",
  "CANULA TRAQUEAL N° 8 C/ ASP. SUBGLIOTICA",
  "CARBAMAZEPINA 200 MG COMPRIMIDOS",
  "Carvedilol 12,5 mg",
  "CARVEDILOL 12,5 MG COMP.",
  "Carvedilol 3,125 mg",
  "CARVEDILOL 3.125 MG COMP.",
  "Carvedilol 6,25 mg",
  "CARVEDILOL 6.25 MG COMP",
  "CATETER DE HEMODIALISIS 12F 20CM",
  "CATETER STENT BILIAR",
  "CATETER URETRAL 6F",
  "CATGUT CROMADO 0",
  "CATGUT CROMADO 1",
  "CATGUT CROMADO 2",
  "CATGUT CROMADO 2/0",
  "CATGUT CROMADO 3/0",
  "CATGUT SIMPLE 0",
  "CATGUT SIMPLE 1",
  "CATGUT SIMPLE 2",
  "CATGUT SIMPLE 2/0",
  "CATGUT SIMPLE 3/0",
  "CEFALEXINA 500MG COMP.",
  "CEFALOTINA 1 G FA",
  "Cefalotina 1 gr",
  "CEFOTAXIMA 1 G F.A.",
  "CEFTAZIDIMA 1 G F.A.",
  "Ceftazidima 1 gr",
  "CEFTRIAXONA 1 G FA",
  "Ceftriaxona 1 gr",
  "CEPILLO PARA HUESO",
  "Cera para hueso",
  "CERA PARA HUESO 2.5 GRS",
  "CHATA PLASTICA",
  "Cilostazol 100 mg",
  "CILOSTAZOL 100 MG COMP.",
  "CILOSTAZOL 50 MG COMP.",
  "Cinitaprida 1 mg",
  "CINITAPRIDA COMP.",
  "CINTA HIPOALERGENICA 2,5CM",
  "CINTA HIPOALERGENICA 5 CM",
  "CINTA HIPOALERGENICA MACROPOROSA 5CM",
  "CINTA TELA ADHESIVA 5CM",
  "CINTA TESTIGO AUTOCLAVE",
  "CINTA TESTIGO ESTUFA",
  "CINTA TESTIGO OXIDO DE ETILENO",
  "Ciprofloxacina 200 mg (sachet)",
  "CIPROFLOXACINA 200 MG/100 ML SACHET",
  "CIPROFLOXACINA 500 MG COMPRIMIDOS",
  "Circuito corrugado para ARM",
  "CIRCUITO CORRUGADO PARA RESPIRADOR",
  "CIRCUITO DE ANESTESIA JACKS-REES C/BOLSA 2 LTS.",
  "Circuito de Aspiracion cerrada 16 Fr",
  "Claritromicina 500 mg",
  "CLARITROMICINA 500 MG COMPRIMIDOS",
  "CLARITROMICINA 500 MG FA",
  "CLINDAMICINA 300 MG COMPRIMIDOS",
  "Clindamicina 600 mg",
  "CLINDAMICINA 600 MG/4 ML AMPOLLA",
  "CLIPMED TITANIO X 6",
  "Clonazepan 0,5 mg",
  "CLONAZEPAN 0,5 MG COMPRIMIDOS",
  "Clonazepan 2 mg",
  "CLONIDINA AMPOLLA",
  "Clopidogrel 75 mg",
  "CLOPIDOGREL 75 MG COMPRIMIDOS",
  "CLORHEXIDINA 500ML",
  "CLORPROMAZINA 50 MG AMPOLLA",
  "CLORURO DE POTASIO 15 MEQ AMPOLLA",
  "Cloruro de Potasio 5 ml",
  "Cloruro de Sodio 20% 10 ml",
  "CLORURO DE SODIO 20% AMP",
  "COFIAS",
  "COLISTINA 100 MG FA",
  "COMPLEJO VITAMINA B",
  "CONJUNTO DE TRANSFUSION T20",
  "Conteiner para alimenacion enteral 500cc",
  "Crema de Bismuto fco 90 ml",
  "CREMA DE BISMUTO SUSPENSION X 90 ML",
  "CUBRE CAMILLAS",
  "Deltisona B 40 mg",
  "Deltisona B 8 mg",
  "DESCARTADOR 4 LTS",
  "DETERGENTE MULTIENZIMATICO 5LT",
  "DETERGENTE TRIENZIMATICO X 1LT",
  "DEXAMETASONA 0,5MG COMP",
  "Dexametasona 8 mg",
  "DEXAMETASONA 8 MG/2 ML AMPOLLA",
  "DIAZEPAM 10 MG AMPOLLA",
  "Diazepan 10 mg",
  "Diazepan 5 mg",
  "Diclofenac 75 mg",
  "DICLOFENAC 75MG AMP",
  "DICLOFENAC 75MG COMP",
  "Difenhidramina 10 mg",
  "DIFENHIDRAMINA 10 MG/1 ML AMPOLLA",
  "DIFENHIDRAMINA 50 MG COMPRIMIDOS",
  "Digoxina 0,25 mg",
  "DIGOXINA 0.25 MG COMPRIMIDOS",
  "DIGOXINA AMPOLLA",
  "DIOSMINA 500MG COMP",
  "DIPIRONA 1 G/2 ML AMPOLLA",
  "Dipirona 1 gr",
  "DIPIRONA COMP.",
  "DOBLE J",
  "DOBUTAMINA 250 MG FA",
  "Dobutamina 250mg/20ml",
  "DOMPERIDONA COMP.",
  "DOPAMINA 200 MG AMPOLLA",
  "ELECTRODOS",
  "Enalapril 10 mg",
  "ENALAPRIL 10 MG COMPRIMIDOS",
  "Enalapril 2,5 mg",
  "Enalapril 5 mg",
  "Enoxaparina 0,40 mg",
  "Enoxaparina 0,60 mg",
  "Enoxaparina 0,80 mg",
  "Enoxaparina 100 mg",
  "ENOXAPARINA 40 MG. JGA PRELL.",
  "ENOXAPARINA 60 MG. JGA PRELL.",
  "ENOXAPARINA 80 MG. JGA PRELL.",
  "Eplerenona 25 mg",
  "EPP",
  "ERITROMICINA 400 COMP.",
  "Espironolactona 100 mg",
  "ESPIRONOLACTONA 100MG COMP",
  "Espironolactona 25 mg",
  "ESPIRONOLACTONA 25 MG COMPRIMIDOS",
  "Espironolactona 50 mg",
  "ESPIRONOLACTONA 50 MG COMPRIMIDOS",
  "ESPONJA HEMOSTATICA",
  "ESTETOSCOPIO",
  "ETILEFRINA 10 MG/1 ML AMPOLLA",
  "Etilefrina 10 mg/ml",
  "Fenitoina 100 mg",
  "FENITOINA 100MG COMPRIMIDOS",
  "FENITOINA100 MG/2 ML AMPOLLA",
  "FENTANILO 0.25 MG/5 ML AMPOLLA",
  "Fentanilo 250 mg",
  "Filtro Bactereologico para ARM",
  "FILTRO BACTERIANO",
  "FILTRO HUMIDIFICADOR",
  "Filtro Humidificador para ARM",
  "Floratil 250 mg",
  "FLORATIL COMP",
  "FLUCONAZOL 150 MG COMPRIMIDOS",
  "FLUCONAZOL 200 MG/100 ML SACHET",
  "Fluconazol 200mg/100 ml (sachet)",
  "Flumazenil 0,5 mg/ml",
  "FLUMAZENIL 0.5 MG/5 ML AMPOLLA",
  "FOGARTY 4FR",
  "FOGARTY 5FR",
  "FORMOL X 1 LTS",
  "FOSFATO DE SODIO SOL. ORAL",
  "FRASCO BITIBULADO 750CC",
  "Frasco Bitubulado 250 ml",
  "FRASCO DE MUESTRA ESTERIL",
  "Furosemida 20 mg",
  "FUROSEMIDA 20 MG/2 ML AMPOLLA",
  "Furosemida 40 mg",
  "FUROSEMIDA 40 MG COMPRIMIDOS",
  "GASA EN PIEZA",
  "Gasas Nitrofurascinadas 0,2% caja x 20 apositos",
  "GEL BUCAL",
  "GEL NEUTRO X 1LT",
  "Gelafundin 4% 500",
  "GELAFUNDIN 500 ml 4% EXP.PLASM.",
  "Gentamicina 80 mg",
  "GENTAMICINA 80 MG/1 ML AMPOLLA",
  "GLUCONATO DE CALCIO 10 %/10 ML AMPOLLA",
  "Gluconato de Calcio 10% 10 ml",
  "GLUCONATO DE POTASIO JBE.",
  "Glucosado Hipert.25% 10 ml",
  "Glucosado Hipert.50% 10 ml",
  "GLUTARALDEHIDO 2% X 1LT",
  "GLUTARALDEHIDO 2% X 5 LTS",
  "Guante esteril N° 6,5",
  "Guante esteril N° 7",
  "Guante esteril N° 7,5",
  "Guante esteril N° 8",
  "Guante esteril N° 8,5",
  "GUANTES DE EXAMEN L",
  "GUANTES DE EXAMEN M",
  "GUANTES DE EXAMEN S",
  "GUANTES DE LATEX XS",
  "GUANTES ESTERILES N° 6.5",
  "GUANTES ESTERILES Nº7",
  "GUANTES ESTERILES Nº7.5",
  "GUANTES ESTERILES Nº8",
  "GUANTES ESTERILES Nº8.5",
  "GUANTES NITRILO ESTERIL L",
  "GUANTES NITRILO ESTERIL M",
  "GUANTES NITRILO ESTERIL S",
  "GUANTES NITRILO L",
  "GUANTES NITRILO M",
  "GUANTES NITRILO S",
  "Hallopurinol 150 mg",
  "Haloperidol 2mg/ml fco 30 ml (gotas)",
  "Haloperidol 5 mg",
  "HALOPERIDOL 5 MG/1 ML AMPOLLA",
  "HEPARINA 10ML",
  "HEPARINA 5000 UI F.A. 5ML",
  "Heparina Sodica 5 ml",
  "Hidroclorotiazida 12,5",
  "Hidroclorotiazida 25 mg",
  "HIDROCLOROTIAZIDA 50 MG COMPRIMIDOS",
  "HIDROCLOROTIAZIDA COMPRIMIDOS",
  "Hidrocortisona 100 mg",
  "HIDROCORTISONA 100 MG FA",
  "Hidrocortisona 500 mg",
  "HIDROCORTISONA 500 MG FA",
  "HILO LINO N° 100",
  "HILO LINO N° 20",
  "HILO LINO N° 30",
  "HILO LINO N° 40",
  "HILO LINO N° 60",
  "HILO LINO N° 70",
  "HILO LINO N° 80",
  "HIOSCINA 10 MG COMPRIMIDOS",
  "Hioscina 20 mg",
  "HIOSCINA 20 MG/1 ML AMPOLLA",
  "HIOSCINA COMPUESTA COMPRIMIDOS",
  "HOJA DE BIST. Nº 11",
  "HOJA DE BIST. Nº 15",
  "HOJA DE BIST. Nº 24",
  "Ibuprofeno 400 mg",
  "IBUPROFENO 600MG COMP.",
  "Imipenem 500 mg",
  "IMIPENEM 500MG FCO. AMP",
  "Insulina H. NPH fco amp 10ml",
  "Insulina H.Cte fco amp 10 ml",
  "INSULINA HUMANA R FCO AMP.",
  "INSULINA LAPICERA DEGLUDEC",
  "INSULINA NPH 100 UI FCO. AMP.",
  "IODO PURO LITRO",
  "IODOPOVIDONA 10% 100ML",
  "IODOPOVIDONA 10% 1L.",
  "IODOPOVIDONA 10% 500ML",
  "IODOPOVIDONA 5% SOL. JAB. 1LTS.",
  "Ipsilon 2gr/10ml",
  "Iruxol-Colagenasa/cloranfenicol 50 gr crema",
  "ISOPROTERENOL 1 MG/5 ML AMPOLLA",
  "Isoproterenol 1mg/5ml",
  "IVERMECTINA 6MG COMP.",
  "JERINGA 10 ML",
  "JERINGA 10 ML CON ROSCA",
  "JERINGA 1ML",
  "JERINGA 20 ML",
  "JERINGA 20ML ROSCA",
  "JERINGA 5 ML CON ROSCA",
  "JERINGA 5ML",
  "Jeringa 60 ml",
  "JERINGA 60ML PICO CORTO",
  "JERINGA 60ML PICO LARGO",
  "JERINGA BONNEAU",
  "K29",
  "K32",
  "Kaon Gluconato de Potasio 31,2 gr fco 150 ml",
  "KETAMINA 500 MG/10 ML FCO. AMP.",
  "Ketamina 500 mg/ml",
  "KETOROLAC 20 MG COMPRIMIDOS",
  "Ketorolac 30 mg",
  "KETOROLAC 30 MG AMPOLLA",
  "Lactulosa jarabe fco 120 ml",
  "LACTULOSA JBE.",
  "Levofloxacina 750 mg",
  "LEVOFLOXACINA COMP.",
  "LEVOTIROXINA 100 MG COMP",
  "Levotiroxina 125 mg",
  "Levotiroxina 50 mg",
  "Levotiroxina 75 mg",
  "LIDOACINA SPRAY 10% 50GR",
  "Lidocaina 2% c/Epinefrina fco 20 ml",
  "Lidocaina 2% fco amp 20 ml",
  "LIDOCAINA CON EPINEFRINA FCO. AMP. X 20 ML",
  "LIDOCAINA JALEA X 25 GR",
  "LIDOCAINA SIN EPINEFRINA FCO. AMP. X 20 ML",
  "LIDOCAINA SPRAY",
  "Llave 3 vias",
  "LLAVE 3 VIAS CON PROLONGADOR",
  "LLAVE DE 3 VIAS",
  "Loperamida 2 mg",
  "LOPERAMIDA 2 MG COMPRIMIDOS",
  "Lorazepan 4 mg",
  "LORAZEPAN 4 MG/1 ML AMPOLLA",
  "Losacor D 100/25 mg",
  "Losartan 100 mg",
  "Losartan 50 mg comp",
  "LOSARTAN 50 MG COMP.",
  "LT 8",
  "MANGO DE ELECTROBISTURI DESCARTABLE",
  "MANOPLAS DE POLIETILENO",
  "Mascara con reservorio",
  "MASCARA FACIAL VNI BORDE INFLABLE",
  "MASCARA LARINGEA N° 5",
  "MASCARA P/OXIGENO C/BOLSA RESERV",
  "MASCARA PARA NEBULIZAR",
  "Mascara VNI adultos",
  "MEMANTINA 10 MG COMP.",
  "Memantine 20 mg",
  "Meprednisona 40 mg",
  "MEPREDNISONA 40 MG COMP.",
  "MEPREDNISONA 8 MG COMP.",
  "MEROPENEM 1 G FA",
  "Meropenem 1 gr",
  "Meropenem 500 mg",
  "MEROPENEM 500 MG FCO AMP",
  "METFORMINA 1GR. COMPRIMIDOS",
  "Metformina 500 mg",
  "Metformina 850 mg",
  "METFORMINA 850 MG COMPRIMIDOS",
  "METILDOPA 500 MG COMPRIMIDOS",
  "Metilprednisolona 500 mg",
  "METILPREDNISOLONA 500 MG FA",
  "Metoclopramida 10 mg",
  "METOCLOPRAMIDA 10 MG/2 ML AMPOLLA",
  "METOCLOPRAMIDA COMPRIMIDOS",
  "Metronidazol 500 mg",
  "Metronidazol 500 mg (sachet)",
  "METRONIDAZOL 500 MG COMP.",
  "METRONIDAZOL 500 MG/100 ML SACHET",
  "MIDAZOLAM 15 MG/3 ML AMPOLLA",
  "Midazolan 15 mg",
  "Miopropan S 200/120 mg",
  "MONONYLON 2/0",
  "MONONYLON 3/0",
  "MONONYLON 4/0",
  "Mononylon 5/0",
  "MORFINA 1%/1 ML AMPOLLA",
  "Morfina 10 mg",
  "N-Acetocisteina 600 mg",
  "NALBUFINA 10MG",
  "NALOXONA 0.4 MG/1 ML AMPOLLA",
  "NEBIVOLOL 10 MG COMPRIMIDOS",
  "NEBIVOLOL 5 MG COMP.",
  "Neostigmina 0,5 mg",
  "NEOSTIGMINA 0,5 MG AMPOLLA",
  "Nevibolol 2,5 mg",
  "Nevibolol 5 mg",
  "NIMODIPINA 30 MG COMP",
  "Nistatina fco 60 ml",
  "NISTATINA SUSPENSION X 60 ML",
  "NITROFURANTOINA 100MG COMP.",
  "NITROFURAZONA CREMA X 500GR",
  "NITROFURAZONA SOL. X 1 LTS",
  "Nitroglicerina 25 mg",
  "NITROGLICERINA 25 MG/5 ML AMPOLLA",
  "Nitroprusiato (NPS) 50 mg",
  "NITROPRUSIATO SODICO 50 MG FA",
  "Noradrenalina 4 mg",
  "NORADRENALINA 4 MG/4 ML AMPOLLA",
  "Nubaina 10 mg",
  "Omeprazol 20 mg",
  "OMEPRAZOL 20 MG. CAPS.",
  "Omeprazol 40 mg",
  "OMEPRAZOL 40 MG FA",
  "ONDASENTRON",
  "Ondasentron 8 mg",
  "Ovata 10 cm",
  "Ovata 15 cm",
  "Ovata 20 cm",
  "OXIDO DE ETILENO 5ML AMP",
  "OXIMETRO DE PULSO",
  "PAÑALES ADULTOS",
  "Pañales descartables XG",
  "PAPAGAYO PLASTICO",
  "PAPEL PARA ENVOLVER CHICO",
  "PAPEL PARA ENVOLVER GRANDE",
  "Paracetamol 1 gr",
  "PARACETAMOL 1GR COMP.",
  "Paracetamol 500 mg",
  "PARACETAMOL 500 MG COMP.",
  "Perfus con regulador de flujo",
  "PERFUS FOTOSENSIBLE",
  "PERFUS MACROGOTERO CON REGULADOR DE FLUJO",
  "PERFUS MICROGOTERO",
  "Perfus N° 1",
  "PERFUS N°1 (MACROGOTERO)",
  "PERFUS P/ ALIMENTACIÓN",
  "Perfus para AE",
  "PERFUS VOLUMETRICO",
  "PINZA HALSTEAD RECTA C/D. X 12.5",
  "Piperacilina Tazobactam 4,5 gr",
  "PIPERACILINA+TAZOBACTAM 4,5 G FA",
  "PLANCHA DE ELECTROBISTURI",
  "Platsul-A crema dermica fco 400 gr",
  "Pregabalina 75 mg",
  "PREGABALINA 75MG COMP.",
  "PROLENE 0",
  "PROLENE 1",
  "PROLENE 2/0",
  "PROLENE 4/0",
  "PROLENE 5/0",
  "PROLENE 6/0",
  "PROLENE 6/0 AGUJA TRIANGULAR",
  "Prolene N° 3/0",
  "Prolongador (PT 26)",
  "PROLONGADOR CON DOS VALVULAS",
  "PROLONGADOR CON REGULADOR DE FLUJO",
  "PROLONGADOR PT26 100CM",
  "PROLONGADOR PT26 50CM",
  "Propanolol 40 mg",
  "PROPANOLOL 40 MG COMP.",
  "Propofol 200 mg/20 ml",
  "PROPOFOL AMP",
  "PROTAMINA 50 MG/5 ML AMPOLLA",
  "PROTESIS VASCULAR",
  "Quetiapina 25 mg",
  "QUETIAPINA 25 MG COMPRIMIDOS",
  "Quetiapina 50 mg",
  "QUETIAPINA 50 MG COMPRIMIDOS",
  "Ranitidina 50 mg",
  "RANITIDINA 50 MG/5 ML AMPOLLA",
  "Remifentanilo 5 mg",
  "REMIFENTANILO 5 MG FA",
  "RESUCITADOR MANUAL ADULTO AMBU",
  "RIFAMPICINA 300 MG CAPS.",
  "RISPERIDONA 1 MG COMP.",
  "Risperidona 2 mg",
  "RISPERIDONA 2 MG COMP.",
  "RISPERIDONA 3 MG COMP.",
  "RIVAROXABAN 10 MG COMPRIMIDOS",
  "Rivaroxaban 15 mg",
  "RIVAROXABAN 15 MG COMPRIMIDOS",
  "Rivaroxaban 20 mg",
  "RIVAROXABAN 20 MG COMPRIMIDOS",
  "ROLLO DE PAPEL PARA ECOGRAFO",
  "ROLLO PAPEL PARA ELECTROCARDIOGRAMA",
  "ROSUVASTATINA 10 MG COMPRIMIDOS",
  "Rosuvastatina 20 mg",
  "ROSUVASTATINA 20 MG COMPRIMIDOS",
  "Rosuvastatina 40 mg",
  "Salbutamol 20 ml (gotas)",
  "Salbutamol 200 mcg/dosis",
  "SALBUTAMOL AEROSOL",
  "SALBUTAMOL GOTAS",
  "Set cateter HD 2 Lumen 12x20Fr (NIPRO)",
  "SET DE VIA CENTRAL 7 F 1 LUMEN",
  "SET DE VIA CENTRAL 7 F 2 LUMEN",
  "Set para Nebulizar",
  "Set para Nebulizar ARM",
  "Set via central 1 Lumen14 Gx200 ml 7 Fr",
  "Set via central 2 Lumen 7 Fr",
  "SET VIA CENTRAL 3 LUMENS",
  "SET VIA CENTRAL 4 FR",
  "SEVORANE 250 ML",
  "Sevorane fco 250 ml",
  "SISTEMA DE ASPIRACION CERRADO 16 FR",
  "SISTEMA DE ASPIRACION CERRADO P/TRAQUEOSTOMIA 16FR",
  "SNG K10",
  "SNG K11",
  "SNG K31",
  "SNG K33",
  "SNG K35",
  "SNG K9",
  "SOL. DEXTROSA 10% 500 ML.",
  "SOL. DEXTROSA AL 25 % X 500 ML",
  "SOL. DEXTROSA AL 5 % X 500 ML",
  "SOL. DEXTROSA al 5% 250 ML.",
  "SOL. FISIOLOGICA 0,9% X 100 ML",
  "SOL. FISIOLOGICA 1000 ML.",
  "SOL. FISIOLOGICA 250 ML.",
  "SOL. FISIOLOGICA X 2000 ML",
  "SOL. FISIOLOGICA X 500 ML.",
  "SOL. GLUCOSADA H 25% 10 ML AMPOLLA",
  "SOL. MANITOL 15% X 500ML.",
  "SOL. RINGER CON LACTATO X 500 ML",
  "SOLUCION BICARBONATO MOLAR X 100ML",
  "Solucion Dextrosa 10% 250 (sachet)",
  "Solucion Dextrosa 10% 500",
  "Solucion Dextrosa 25% 250 (sachet)",
  "Solucion Dextrosa 25% 500",
  "Solucion Dextrosa 5% 100 (sachet)",
  "Solucion Dextrosa 5% 250 (sachet)",
  "Solucion Dextrosa 5%500",
  "Solucion Fisiologica 100 (sachet)",
  "Solucion Fisiologica 1000 (sachet)",
  "Solucion Fisiologica 2000 (sachet)",
  "Solucion Fisiologica 250 (sachet)",
  "Solucion Fisiologica 500",
  "Solucion Ringer Lactato 500",
  "Solucion Topica Iodopovidona 10% fco 1 lt.",
  "SONDA B- 2941 P/ TOMA DE MUESTRAS",
  "SONDA DRENAJE TORAXICO K 225",
  "SONDA DRENAJE TORAXICO K 227",
  "SONDA FOLEY 2 VIAS 12FR",
  "SONDA FOLEY 2 VIAS 16FR",
  "SONDA FOLEY 2 VIAS 16FR SILICONADA",
  "SONDA FOLEY 2 VIAS 18FR",
  "SONDA FOLEY 2 VIAS 18FR SILICONADA",
  "SONDA FOLEY 2 VIAS 20FR",
  "SONDA FOLEY 2 VIAS 22FR",
  "SONDA FOLEY 3 VIAS 16FR",
  "SONDA FOLEY 3 VIAS 18FR",
  "SONDA FOLEY 3 VIAS 20FR",
  "SONDA FOLEY 3 VIAS 22FR",
  "SONDA FOLEY 3 VIAS 24FR",
  "Sonda Foley N° 16",
  "Sonda Foley N° 18",
  "Sonda Foley N°12",
  "SONDA K 10",
  "SONDA K 11",
  "SONDA K 29",
  "SONDA K 30",
  "SONDA K 31",
  "SONDA K 32",
  "SONDA K 33",
  "SONDA K 35",
  "SONDA K 9",
  "SONDA NASOYEYUNAL K 108",
  "SONDA NELATON N° 10",
  "SONDA NELATON N° 12",
  "SONDA NELATON N° 14",
  "SONDA NELATON N° 16",
  "SONDA NELATON N° 8",
  "SONDA NELATON N°11",
  "SONDA NELATON N°18",
  "SONDA NELATON N°22",
  "SONDA PEZZER 18FR",
  "SONDA PEZZER 20FR",
  "SONDA PEZZER 24FR",
  "Sonda rectal N° 16",
  "Sonda rectal N° 18",
  "Sonda rectal N° 20",
  "Sonda rectal N° 22",
  "SONDA RECTAL N°22",
  "Spongostan",
  "STENT URETRAL",
  "Succinilcolina 100 mg",
  "SUCCINILCOLINA 100 MG AMPOLLA",
  "Sucralfato 20% fco 200 ml",
  "SUCRALFATO JBE",
  "SULFADIAZINA DE PLATA CREMA 350 G",
  "SULFAMETOXAZOL + TRIMETOPRIMA AMPOLLA",
  "SULFAMETOXAZOL + TRIMETOPRIMA COMPRIMIDOS",
  "Sulfato de Hierro 200 mg",
  "SULFATO DE MAGNESIO 25% AMPOLLA",
  "Sulfato de Magnesio 5 ml",
  "SURGICEL HEMOSTATICO",
  "Tamsulosina 0,40 mg",
  "TAMSULOSINA COMP 0.4 MG",
  "Tegadem 6 x 7 cm",
  "Tegaderm 10 x 12 cm",
  "Telmisartan 40 mg",
  "TELMISARTAN COMP.",
  "TENSIOMETRO ANAROIDE (BOLSA)",
  "TENSIOMETRO ANAROIDE SIN ESTETOSCOPIO",
  "TENSIOMETRO ANEROIDE C/ESTETOSCOPIO",
  "TENSIOMETRO DIGITAL",
  "TERMOMETRO CLINICO",
  "TERMOMETRO DIGITAL",
  "TERMOMETRO INFRARROJO",
  "TET N° 6,5",
  "TET N° 7",
  "TET N° 7,5",
  "TET N° 8",
  "TIOPENTAL SODICO 1GR FA",
  "Tiras control de glucemia",
  "TIRAS ESTERILIZACIÓN CALOR HUMEDO",
  "TIRAS REACTIVAS ESTERILIZACIóN CALOR SECO",
  "TIRAS REACTIVAS ESTERILIZACIóN OX. DE ETILENO",
  "TIRAS REACTIVAS GO CHEK2",
  "TIRAS REACTIVAS MAVERICK",
  "TIRAS REACTIVAS ON CALL",
  "Tramadol 100 mg",
  "TRAMADOL 100 MG/2 ML AMPOLLA",
  "Tramadol 50 mg",
  "TRAMADOL 50 MG COMPRIMIDOS",
  "TRAMADOL 50 MG/1 ML AMPOLLA",
  "TRIMEBUTINA COMPRIMIDOS",
  "Trimetoprima/Sulfametoxazol (Bactrim) 800/160 mg",
  "TRIYOSOM 50 FCO.AMP.X 50 ML.",
  "TUBO DE KEHR",
  "TUBO DE MAYO N° 2",
  "TUBO DE MAYO N° 3",
  "TUBO DE MAYO N° 4",
  "TUBO DE MAYO N° 5",
  "TUBO DE MAYO N° 6",
  "Tubo de Mayo N° 8",
  "TUBO ENDOTRAQ. 6.5 C/BALON",
  "TUBO ENDOTRAQ. 7 C/BALON",
  "TUBO ENDOTRAQ. 7.5 C/BALON",
  "TUBO ENDOTRAQ. 8 C/BALON",
  "TUBO ENDOTRAQ. 8.5 C/BALON",
  "TUBO T ARM",
  "Tubo T para ARM",
  "Valsartan 160 mg",
  "VALSARTAN 160 MG COMPRIMIDOS",
  "Valsartan 80 mg",
  "VALSARTAN 80 MG COMPRIMIDOS",
  "Valsartan+ HCLZ 160/12,5 mg",
  "Valsartan+ HCLZ 80/12,5mg",
  "Vancomicina 1 gr",
  "VANCOMICINA 1 GR. FCO. AMP",
  "VANCOMICINA 500 MG FCO. AMP.",
  "Vaselina liquida fco 125 ml",
  "VASELINA LIQUIDA X 125ML.",
  "VASELINA LIQUIDA X 1LT.",
  "Vaselina solida fco 60 gr",
  "VASELINA SOLIDA X 1KG",
  "VASELINA SOLIDA X 500MG",
  "VENDA CAMBRIC",
  "VENDA DE GASA 10CM",
  "VENDA DE YESO 10 CM.",
  "Venda de Yeso 10cm",
  "VENDA DE YESO 15 CM.",
  "Venda de Yeso 15cm",
  "Venda de Yeso 20 cm",
  "VENDA DE YESO 20 CM.",
  "VENDA GOMA SMARCH 15 CM",
  "VENDA GOMA SMARCH 20 CM",
  "VENDA OVATA 10 CM",
  "VENDA OVATA 15 CM",
  "VENDA OVATA 20CM",
  "VICRYL 0",
  "VICRYL 1",
  "VICRYL 2",
  "VICRYL 2/0",
  "VICRYL 3/0",
  "VICRYL 4/0",
  "VICRYL 5/0",
  "VICRYL 6/0",
  "Vicryl N° 0",
  "Vicryl N° 1",
  "Vicryl N° 2",
  "Vicryl N° 2/0",
  "Vicryl N°3/0",
  "Vitamina k 10 mg",
  "VITAMINA K 10 MG AMPOLLA",
  "Xilocaina jalea 2%",
]